# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('one_price', models.PositiveSmallIntegerField(verbose_name='Пробное занятие')),
                ('four_price', models.PositiveSmallIntegerField(verbose_name='4 занятия')),
                ('four_price_discount', models.PositiveSmallIntegerField(verbose_name='4 занятия скидкой')),
                ('eight_price', models.PositiveSmallIntegerField(verbose_name='8 занятий')),
                ('eight_price_discount', models.PositiveSmallIntegerField(verbose_name='8 занятий со скидкой')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('for_group', models.CharField(max_length=30, verbose_name='Для кого?')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Price', verbose_name='Цены')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
