# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_programs_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=250, null=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('draft', models.BooleanField(default=False)),
            ],
        ),
    ]
