# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 09:19
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
